name: gwflow

channels:
  - conda-forge

dependencies:

  # primary dependencies
  - python>=3.12
  - git

  # jupyter dependencies
  - jupyter
  - jupyterlab

  # scipy stack
  - numpy
  - pandas
  - matplotlib<=3.10
  - scipy